### ISSUE TITLE
As a user, I want a relevant landing page, so that I can immediately either play a game, or learn how to.

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#11]
Work required for this story, is to strip out the pre-existing code for the "home" page of the site, and replace it with the correct home page.

**Comment by DeanKuhne** [comment]
Nav Bar and Contact page have been completed and merged into master. Make sure you merge DEVELOP into your branch before continuing.

Be sure you merge develop into your branch, and NOT the other way around yet.
This can be done by checking out your branch, right clicking on the Develop tag in GitKraken, and selecting Merge Develop into your branch.

**Comment by DeanKuhne** [comment]
code review complete, everything looks good.

**Comment by DeanKuhne** [comment]
for UI review, created Issue 25 (the main menu button does not do anything). Moving back to in progress

**Comment by DeanKuhne** [comment]
code re-reviewed. everything is good. merging to develop

**Comment by DeanKuhne** [comment]
UI review round 2 is accepted. Needs acceptance criteria. Moving to awaiting PM review.

**Comment by KedharGhi** [comment]
Acceptance tests are as follows:
1) The landing page should have a blurred map of US with two clickable buttons.
2) The play button should take you to game selection page.
3) How to play button will take you to instructions on how to play the game.
4) On the game selection page, main menu should bring you back to landing page.
5) Landing Page, Game Selection Page and Instructions Page should be mobile friendly.
