### ISSUE TITLE
As a user, I want to be able to learn about the team responsible for the site, so that I can be inspired

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#12]
Relevant work for this is to create the "About the Team" page that is linked to the "about the team" option on the nav bar.

**Comment by DeanKuhne** [comment]
Nav Bar and Contact page have been completed and merged into master. Make sure you merge DEVELOP into your branch before continuing.

Be sure you merge develop into your branch, and NOT the other way around yet.
This can be done by checking out your branch, right clicking on the Develop tag in GitKraken, and selecting Merge Develop into your branch.

**Comment by DeanKuhne** [comment]
code review done, everything looks good. merging into develop.

**Comment by DeanKuhne** [comment]
ready for PM review, needs acceptance criteria.

**Comment by Prometheus66** [comment]
Acceptance tests are as follows:
1) The About the Team page should be accessible via the nav bar on every page, under further information.
2) Clicking on the link for the About the Team page should bring the user to the correct page.
3) The user should be able to easily identify what description is aimed at which developer.
