### ISSUE TITLE
As a user, I want a scoreboard page, so that I can brag to my classmates.

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#13]
Relevant work is to complete a page that is linked to the "Scoreboard" option on the nav bar. 

We want a list that has the fields Name/Score/Gamemode/Date.

**Comment by DeanKuhne** [comment]
If you are completed with this issue, be sure to change it's status in the pipeline by dragging it to the correct stage. (Also, as per our discussions at the end of Monday's meeting, it would be nice to have some dummy data forming a list on a grid)

Name   |   Score  |   Mode     |     Date of Score          |          Completion Time

Essentially, a grid with those column names populated with some dummy data. @eykim5

**Comment by DeanKuhne** [comment]
Nav Bar and Contact page have been completed and merged into master. Make sure you merge DEVELOP into your branch before continuing.

Be sure you merge develop into your branch, and NOT the other way around yet.
This can be done by checking out your branch, right clicking on the Develop tag in GitKraken, and selecting Merge Develop into your branch.

**Comment by eykim5** [comment]
Acceptance tests are as follows:
1) The scoreboard page should be immediately identifiable and accessible under the nav bar for every page of the website.
2) Clicking on the scoreboard link should lead to the correct page.
3) The scoreboard page should contain a table that has the following fields: Username | Score | Mode | Date | Completion Time

**Comment by DeanKuhne** [comment]
code review looks good, merging to developement.

**Comment by DeanKuhne** [comment]
UI reviewed after merging into develop, all good. moving to awaiting PM review.
