### ISSUE TITLE
As a user, I want a working US States gamemode, so that I have a basic, working game to play.

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#30]

**Comment by eykim5** [comment]
Acceptance tests:

1a) From the Game Selection menu, only US States should be selectable as a game. The two option boxes below should say that that game is coming soon.

1) Clicking on US States should open up a page with the US map displayed, with a module that prompts the player on information relevant to the game mode selected.

2) Clicking the start button from the aforementioned module should begin the game, with the timer counting down from 10 minutes to zero.

3) Hovering over a state should make it highlight blue. Currently selected states highlight yellow, then correct states highlight green while incorrect states highlight red after answering.

4) Selecting a state opens up a module where an image of the currently selected state is visible, along with a "back" and "submit" button. The user should be able to input a response in a textbox; the correct answer is the name of the current state (not case sensitive). Clicking back will cancel out the module, while clicking submit will determine if the answer is correct or not.

5) A current score is displayed at all times underneath the timer, and is regularly updated every time the user attempts to identify a state. Scoring is as follows:
+5 for correct state.
-2 for incorrect state.
+1 for each 5 sec remaining on timer. (Applies at end of game).

6) A game over module appears once the player either attempts all 50 states or time runs out. The timer should stop at this moment. The module should display the final score the user has earned as well as the completion time. Below are the "try again" and "main menu" buttons, which refreshes the page back to the starting prompt and returns the user to the main menu respectively.
