### ISSUE TITLE
As a developer, I want a backend so that I can transmit data to and from the frontend to a server.

### ISSUE THREAD

**Issue by KedharGhi** [cse442-fall-2019-offering/442projects-team-450#43]

**Comment by DeanKuhne** [comment]
Moving to backlog since we won't have it completed in time for sprint two.

**Comment by DeanKuhne** [comment]
Acceptance criteria:
1.) Backend should only contain the Database setup and table contents.
2.) Backend does not throw any errors while running.
3.) Currently on the Scoreboard page, we want to test the current database connection via an Edit and Delete button next to each scoreboard entry, as well as add new scoreboard entries. This will allow us to test our backend connection.
