### ISSUE TITLE
As a developer, I would like to create a relational database schema for the scoreboard with all the necessary attributes [Username, Score, Time, Date, Mode].

### ISSUE THREAD

**Issue by KedharGhi** [cse442-fall-2019-offering/442projects-team-450#48]

**Comment by DeanKuhne** [comment]
Acceptance Criteria:
Scoreboard table should map to a Scoreboard model object.
It's data and object types should be as follows:
ID: int,
Username: String,
Score: String,
Date: DateTime,
Mode: String,
CompletionTime: String.
