### ISSUE TITLE
Modify scoreboard page to have a selector for displaying different game mode's high scores

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#63]
There should be a selector for each game mode type, after selecting this, the respective high scores should be shown.

**Comment by KedharGhi** [comment]
Acceptance Tests:
-> There should be three buttons for the different games modes.
-> Each button corresponds to table of its own game mode, clicking the buttons should take you to the page where only that game mode highest scores are displayed.
