### ISSUE TITLE
As a user, I would like to be able to contact the developers if I run into issues with the website.

### ISSUE THREAD

**Issue by Prometheus66** [cse442-fall-2019-offering/442projects-team-450#7]

**Comment by DeanKuhne** [comment]
Code review done by me, everything looks good.

**Comment by Prometheus66** [comment]
Acceptance tests are as follows:
1) The Contacts page should be accessible via the nav bar on every page, under further information.
2) Clicking on the link for the Contacts Page should bring the user to the Contacts Page.
3) On the Contacts Page, there should be information with what email address to use under what circumstance.
