### ISSUE TITLE
As a developer, I would like to know the UI design, so that my code is consistent with requirements.

### ISSUE THREAD

**Issue by Prometheus66** [cse442-fall-2019-offering/442projects-team-450#8]

**Comment by DeanKuhne** [comment]
Header Bar Design => ![Header Bar.png](https://images.zenhubusercontent.com/5d767b020feda30001c7f537/a7a065bc-276a-426b-80ba-5fecbca67041)

**Comment by DeanKuhne** [comment]
We want a place to see a mockup of the website.

**Comment by ebrown13** [comment]
![442 UI Mock up.jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/b846c132-309b-4f75-a44b-2958f7e48263)![442 UI Play Page.jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/85ec9e50-e869-4304-aece-74c93b2421a7)![442 UI About Page.jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/ada3f0c2-b8ae-4758-b66b-a8d3543d56ab)![442 UI Contact Us.jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/ce35c865-2329-4608-9078-54ab549417cf)

**Comment by ebrown13** [comment]
UI Mock ups v2

![442 UI Mock up (3).jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/0f77c80a-359a-4fee-ae93-aa0418da2b1b)![442 UI Play Page (1).jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/17d0f296-37f1-4384-b0e1-e703468f89e5)![442 UI About Page (1).jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/59337c34-8355-4a16-bd53-f10d67f13c6c)![442 UI Contact Us (1).jpg](https://images.zenhubusercontent.com/5d72739895c1f100010864c3/e1595649-3269-4e8e-9f31-2f9763438839)
