### ISSUE TITLE
As a user, I want a site with consistent styles such that it is nicer to look at

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#80]
This includes making buttons look identitical, as well as making the site feel less empty with some smooth color palettes.

**Comment by DeanKuhne** [comment]
first request, we'd like to have a favicon for the tab

**Comment by KedharGhi** [comment]
Acceptance Tests:
-> For every page, there should be a fevicon of a world on the tab.
-> Buttons should have a consistent styles throughout the pages.
