### ISSUE TITLE
As a user, I want a header bar so that I can navigate the different pages of the site.

### ISSUE THREAD

**Issue by DeanKuhne** [cse442-fall-2019-offering/442projects-team-450#9]
Subtask for Issue 8. See Issue 8 for description of work for this specific part.
![Header Bar.png](https://images.zenhubusercontent.com/5d767b020feda30001c7f537/220c1ee8-d381-4951-a78a-17959116690d)

**Comment by DeanKuhne** [comment]
Due to desired UI changes, the hamburger glyphicons indicating a menu is a dropdown are now down arrow glyphicons.

In addition, "Play Now" is now called "Game Selection".

**Comment by DeanKuhne** [comment]
Acceptance tests are as follows:
1.) Three sections for the nav bar: Game Selection, Scoreboard, and Further Information.
2.) Game Selection and Further Information should have a down arrow glyphicon next to the words.
3.) Dropdown menu should work properly both on desktop and mobile devices.
4.) Game Selection Dropdown menu contains game options, but these should not link to anything yet.
5.) Once the other pages are merged in, the Scoreboard, and both options under Further Information should direct user to proper page.

**Comment by Prometheus66** [comment]
Meant to comment earlier when I merged, but the code review was fine.  Everything looks good.
